/* ============================================================
   DATA — familles créoles + UI labels i18n
   ============================================================ */

export const FAMILIES = {
  kilti: {
    name:"Kilti", nameClass:"", base:"FR-based",
    eyebrow:"Lang péyi nou", title:"Aprann Kréyòl",
    sub:"Guadeloupe · Martinique · Réunion · Maurice · Louisiane · Haïti",
    btnP:"Kòmansé dèpi zéro", btnS:"Mwen ja ka konpwann",
    baseline:"Aprann kréyòl — Learn Creole",
    desc:"French-based creoles are spoken by over 12 million people. Born from French with African, Amerindian and Malagasy substrata.",
    speakers:"12M+", audioLbl:"Tann fraz-la", footer:"Kréyòl sé lang nou.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Aprann Kréyòl",
      culture:   "Kilti Kréyòl",
      apropos:   "Ki nou yé ?",
      communaute:"Ansanm nou fò",
    },
    heroSubs:{
      langue:    "Guadeloupe · Martinique · Réunion · Maurice · Louisiane · Haïti",
      culture:   "Cuisine · Musique · Voyage",
      apropos:   "La plateforme de toutes les languesv et cultures créoles",
      communaute:"Journal de bord · Livre d'or",
    },
    creoles:[
      {iso:"gcf",name:"Gwadloupéyen",full:"Kréyòl Gwadloup", btnP:"Koumansé a zéwo", btnS:"Mwen ja ka konprann"},
      {iso:"gcf",name:"Matiniké",full:"Kréyòl Matnik", btnP:"Koumansé a zéwo", btnS:"Mwen ja ka konprann"},
      {iso:"hat",name:"Haïtien",full:"Kreyòl ayisyen", btnP:"Kòmanse nan zewo", btnS:"Mwen deja konprann"},
      {iso:"rcf",name:"Réyoné",full:"Kréol réinioné", btnP:"Komanse a zero", btnS:"Moin la fine konprann"},
      {iso:"mfe",name:"Morisyen",full:"Kreol Morisyen", btnP:"Koumans a zero", btnS:"Mo deza konpran"},
      {iso:"lou",name:"Lwizyannais",full:"Kréyòl Lwizyàn", btnP:"Kòmans en zéwo", btnS:"Mo ja konprann"},
    ],
    langue:[
      {tag:"Salitasyon",phrase:"Bonjou, kijan ou yé ?",fr:"Bonjour, comment vas-tu ?",iso:"gcf",q:"Que signifie « kijan ou yé ? »",opts:["Comment tu t'appelles ?","Comment vas-tu ?","Où vas-tu ?"],ans:1},
      {tag:"Manjé",phrase:"An vlé on bokit.",fr:"Je veux un bokit.",iso:"gcf",q:"Le bokit est :",opts:["Une boisson","Un sandwich frit","Un dessert"],ans:1},
      {tag:"Tan",phrase:"I ka fè chò.",fr:"Il fait chaud.",iso:"gcf",q:"« chò » =",opts:["Froid","Chaud","Pluie"],ans:1},
    ],
    cuisine:[
      {name:"Bokit",origin:"Guadeloupe · gcf",desc:"Pain frit garnis, street-food n°1.",tag:"Snack",diff:"Facile"},
      {name:"Colombo",origin:"Martinique · gcf",desc:"Cari aux épices indiennes, poulet ou cabri.",tag:"Plat",diff:"Moyen"},
      {name:"Accras de morue",origin:"Antilles · gcf",desc:"Beignets de morue épicés, apéritif incontournable.",tag:"Apéro",diff:"Facile"},
    ],
    voyage:[
      {sit:"Aéroport",phrase:"Kote toilet-la yé ?",fr:"Où sont les toilettes ?",note:"Indispensable à l'arrivée."},
      {sit:"Marché",phrase:"Sa ka kouté ?",fr:"Combien ça coûte ?",note:"Marchandage amical."},
      {sit:"Taxi",phrase:"Mennen mwen la, souplé.",fr:"Emmenez-moi là-bas, s'il vous plaît.",note:"Poli et efficace."},
    ],
    musique:[
      {name:"Zouk",origin:"Guadeloupe/Martinique",desc:"Né avec Kassav' (1980s). Fusion cadence, funk, compas.",tag:"Danse",diff:"Iconique"},
      {name:"Gwo Ka",origin:"Guadeloupe",desc:"7 rythmes, tambour ka, chant répondè. UNESCO.",tag:"Patrimoine",diff:"Racines"},
      {name:"Bèlè",origin:"Martinique",desc:"Tambour et ti-bwa, danse de lutte.",tag:"Tradition",diff:"Rituel"},
      {name:"Sega",origin:"Maurice/Réunion",desc:"Ravanne, triangle, chant créole océan Indien.",tag:"Océan Indien",diff:"Populaire"},
      {name:"Compas",origin:"Haïti",desc:"Créé par Nemours Jean-Baptiste, base du konpa moderne.",tag:"Haïti",diff:"Incontournable"},
    ],
  },

  kalcha: {
    name:"Kalcha", base:"EN-based",
    eyebrow:"Island tongue", title:"Learn Creole English",
    sub:"Jamaica · Trinidad · Belize · Nigeria",
    btnP:"Start from scratch", btnS:"I already understand",
    baseline:"Kalcha — English-based Creoles",
    desc:"English-based creoles across Caribbean, Africa and Pacific.",
    speakers:"8M+", audioLbl:"Listen phrase", footer:"Kalcha is our voice.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Learn Creole English",
      culture:   "Kalcha Culture",
      apropos:   "Who we are",
      communaute:"Community",
    },
    heroSubs:{
      langue:    "Jamaica · Trinidad · Belize · Nigeria",
      culture:   "Food · Music · Travel",
      apropos:   "All the world's creoles, one platform",
      communaute:"Guestbook · Journal",
    },
    creoles:[
      {iso:"jam",name:"Jamaican",full:"Patois", btnP:"Start from scratch", btnS:"I already understand"},
      {iso:"trf",name:"Trinidadian",full:"Trini Creole", btnP:"Start from scratch", btnS:"I already understand"},
      {iso:"pcm",name:"Nigerian",full:"Naija Pidgin", btnP:"Start from scratch", btnS:"I already understand"},
    ],
    langue:[
      {tag:"Greeting",phrase:"Wah gwaan?",fr:"What's up?",iso:"jam",q:"Meaning?",opts:["Goodbye","What's up?","Thanks"],ans:1},
    ],
    cuisine:[
      {name:"Jerk Chicken",origin:"Jamaica",desc:"Scotch bonnet, pimento, slow smoke.",tag:"Grill",diff:"Hard"},
      {name:"Doubles",origin:"Trinidad",desc:"Bara bread, channa curry, pepper sauce.",tag:"Street",diff:"Easy"},
    ],
    voyage:[
      {sit:"Airport",phrase:"How much fi di taxi?",fr:"How much for the taxi?",note:"Always ask before entering."},
      {sit:"Market",phrase:"How much fi dis?",fr:"How much is this?",note:"Universal haggling."},
    ],
    musique:[
      {name:"Reggae",origin:"Jamaica",desc:"Heavy bass, social message. Bob Marley.",tag:"World",diff:"Legend"},
      {name:"Dancehall",origin:"Jamaica",desc:"Sound systems, digital riddims.",tag:"Urban",diff:"Energy"},
      {name:"Calypso",origin:"Trinidad",desc:"Carnival satire, steelpan.",tag:"Carnival",diff:"Roots"},
      {name:"Soca",origin:"Trinidad",desc:"Soul+Calypso, king of carnival.",tag:"Party",diff:"Popular"},
      {name:"Afrobeats Pidgin",origin:"Nigeria",desc:"Naija pidgin on afro beats.",tag:"Africa",diff:"Modern"},
    ],
  },

  'kultura-pt': {
    name:"Kultura", nameClass:"", base:"PT-based",
    eyebrow:"Língua do povo", title:"Aprende o Crioulo",
    sub:"Cabo Verde · Guiné-Bissau · Malacca",
    btnP:"Kumesa di zero", btnS:"N dja papia",
    baseline:"Kultura PT — Portuguese-based Creoles",
    desc:"Portuguese-based creoles across Atlantic and Indian Ocean routes.",
    speakers:"2M+", audioLbl:"Uvi frazi", footer:"Kultura PT é nha raiz.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Aprende o Crioulo",
      culture:   "Kultura Criola",
      apropos:   "Kén nu é?",
      communaute:"Komunidade",
    },
    heroSubs:{
      langue:    "Cabo Verde · Guiné-Bissau · Malacca",
      culture:   "Kuzinha · Múzika · Viaji",
      apropos:   "Tudu kriol di mundu, un plataforma",
      communaute:"Diáriu · Livru d'oru",
    },
    creoles:[
      {iso:"kea",name:"Kabuverdianu",full:"Cabo Verde", btnP:"Kumesa di zero", btnS:"N dja papia"},
      {iso:"pov",name:"Guinéense",full:"Guinea-Bissau", btnP:"Kumesa di zero", btnS:"N dja papia"},
      {iso:"mcm",name:"Kristang",full:"Malacca", btnP:"Kumesa di zero", btnS:"N dja papia"},
    ],
    langue:[
      {tag:"Saudação",phrase:"Modi bu sta?",fr:"Comment vas-tu?",iso:"kea",q:"Modi =",opts:["Où","Comment","Quand"],ans:1},
      {tag:"Mercado",phrase:"I sta dretu.",fr:"Je vais bien.",iso:"pov",q:"« dretu » veut dire:",opts:["bien","vite","loin"],ans:0},
      {tag:"Casa",phrase:"Bos teng fome?",fr:"Tu as faim?",iso:"mcm",q:"« fome » =",opts:["soif","faim","sommeil"],ans:1},
    ],
    cuisine:[
      {name:"Kachupa",origin:"Cabo Verde",desc:"Ragoût maïs/haricots, plat national.",tag:"Plat",diff:"Moyen"},
    ],
    voyage:[
      {sit:"Mercado",phrase:"Kantu ki e?",fr:"Combien?",note:"Cap-Vert."},
      {sit:"Rua",phrase:"Undi ki bu ta bai?",fr:"Où vas-tu?",note:"Salutation informelle."},
    ],
    musique:[
      {name:"Morna",origin:"Cabo Verde",desc:"Cesária Évora. Saudade créole.",tag:"UNESCO",diff:"Âme"},
      {name:"Funaná",origin:"Cabo Verde",desc:"Accordéon, ferrinho. Rythme paysan.",tag:"Danse",diff:"Rapide"},
      {name:"Jingkli Nona",origin:"Malacca",desc:"Chant kristang d'origine luso-asiatique.",tag:"Patrimoine",diff:"Rare"},
    ],
  },

  'kultura-es': {
    name:"Kultura", nameClass:"", base:"ES-based",
    eyebrow:"Lengua del pueblo", title:"Aprende el Criollo",
    sub:"Caribe hispano · Chabacano · Papiamentu",
    btnP:"Empieza desde cero", btnS:"Ya entiendo",
    baseline:"Kultura ES — Spanish-based Creoles",
    desc:"Spanish-based creoles and Iberian-contact varieties.",
    speakers:"1M+", audioLbl:"Escucha frase", footer:"Kultura ES es nuestra voz.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Aprende el Criollo",
      culture:   "Kultura Criolla",
      apropos:   "¿Quiénes somos?",
      communaute:"Comunidad",
    },
    heroSubs:{
      langue:    "Caribe hispano · Chabacano · Papiamentu",
      culture:   "Cocina · Música · Viaje",
      apropos:   "Todos los criollos del mundo, una plataforma",
      communaute:"Diario · Libro de visitas",
    },
    creoles:[
      {iso:"ckz",name:"Chabacano",full:"Zamboanga", btnP:"Empieza desde cero", btnS:"Ya entiendo"},
      {iso:"pap",name:"Papiamentu",full:"ABC Islands", btnP:"Empieza desde cero", btnS:"Ya entiendo"},
    ],
    langue:[
      {tag:"Saludo",phrase:"Kosa ta pasa?",fr:"Que se passe-t-il ?",iso:"pap",q:"« Kosa ta pasa » =",opts:["Comment ça va","D'où viens-tu","À bientôt"],ans:0},
      {tag:"Calle",phrase:"Onde tu anda?",fr:"Où vas-tu ?",iso:"ckz",q:"« onde » significa:",opts:["dónde","por qué","cuándo"],ans:0},
    ],
    cuisine:[
      {name:"Sancocho criollo",origin:"Caribe hispano",desc:"Ragoût rustique, légumes et viande.",tag:"Plat",diff:"Moyen"},
    ],
    voyage:[
      {sit:"Barrio",phrase:"Kuanto ese?",fr:"Combien ça coûte ?",note:"Usage courant."},
      {sit:"Playa",phrase:"Unda bo ta bai?",fr:"Où vas-tu?",note:"Papiamentu informel."},
    ],
    musique:[
      {name:"Tumba",origin:"Curaçao",desc:"Rythme de carnaval en papiamentu.",tag:"Carnaval",diff:"Festif"},
      {name:"Chabacano Pop",origin:"Zamboanga",desc:"Pop locale con refrains criollos.",tag:"Urbain",diff:"Moderne"},
    ],
  },

  'kultura-nl': {
    name:"Kultura", nameClass:"", base:"NL-based",
    eyebrow:"Taal van het volk", title:"Leer Creools",
    sub:"Dutch-contact · Caribbean · Guyana",
    btnP:"Begin vanaf nul", btnS:"Ik begrijp al",
    baseline:"Kultura NL — Dutch-based Creoles",
    desc:"Dutch-based and Dutch-contact creoles from Atlantic history.",
    speakers:"0.5M+", audioLbl:"Luister zin", footer:"Kultura NL leeft voort.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Leer Creools",
      culture:   "Creoolse Cultuur",
      apropos:   "Wie zijn wij?",
      communaute:"Gemeenschap",
    },
    heroSubs:{
      langue:    "Dutch-contact · Caribbean · Guyana",
      culture:   "Keuken · Muziek · Reizen",
      apropos:   "Alle creoolse talen, één platform",
      communaute:"Dagboek · Gastenboek",
    },
    creoles:[
      {iso:"skw",name:"Skepi",full:"Guyana", btnP:"Begin vanaf nul", btnS:"Ik begrijp al"},
      {iso:"brc",name:"Berbice",full:"Guyana", btnP:"Begin vanaf nul", btnS:"Ik begrijp al"},
    ],
    langue:[
      {tag:"Groet",phrase:"Fa yu de?",fr:"Comment vas-tu ?",iso:"skw",q:"« Fa » betekent:",opts:["hoe","morgen","weer"],ans:0},
      {tag:"Markt",phrase:"Mi wani bai na winkel.",fr:"Je veux aller au magasin.",iso:"brc",q:"« wani » =",opts:["willen","moeten","weten"],ans:0},
    ],
    cuisine:[
      {name:"Pastechi creool",origin:"Dutch Caribbean",desc:"Petits chaussons frits, version locale.",tag:"Snack",diff:"Facile"},
    ],
    voyage:[
      {sit:"Straat",phrase:"Fa yu de tide?",fr:"Comment vas-tu aujourd'hui ?",note:"Formule amicale."},
      {sit:"Winkel",phrase:"Wan prijs?",fr:"Quel prix ?",note:"Direct et efficace."},
    ],
    musique:[
      {name:"Tambú",origin:"Curaçao",desc:"Percussions profondes et chant responsorial.",tag:"Racines",diff:"Intense"},
      {name:"Kaseko",origin:"Suriname",desc:"Fanfare créole, groove dansant.",tag:"Danse",diff:"Classique"},
    ],
  },

  takafa: {
    name:"تكافا", nameClass:"logo-ar", base:"AR-based",
    eyebrow:"لغة الشعب", title:"تعلم العربية الكريولية", titleClass:"title-ar",
    sub:"Juba · Nubi · Soudan",
    btnP:"ابدأ من الصفر", btnS:"أنا أفهم",
    baseline:"تكافا — Creoles arabes",
    desc:"Arabic-based pidgins of East Africa.",
    speakers:"2M+", audioLbl:"استمع للجملة", footer:".تكافا هي جذورنا",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "تعلم العربية الكريولية",
      culture:   "ثقافة تكافا",
      apropos:   "من نحن؟",
      communaute:"المجتمع",
    },
    heroSubs:{
      langue:    "Juba · Nubi · Soudan",
      culture:   "مطبخ · موسيقى · سفر",
      apropos:   "كل الكريول في العالم، منصة واحدة",
      communaute:"مذكرات · سجل الزوار",
    },
    creoles:[
      {iso:"pga",name:"Juba",full:"Juba Arabic", btnP:"ابدأ من الصفر", btnS:"أنا أفهم"},
      {iso:"nub",name:"Nubi",full:"Kenya/Uganda", btnP:"ابدأ من الصفر", btnS:"أنا أفهم"},
    ],
    langue:[
      {tag:"تحية",phrase:"Keif halak?",fr:"Comment vas-tu?",iso:"pga",q:"معنى",opts:["مرحبا","كيف حالك","شكرا"],ans:1},
    ],
    cuisine:[
      {name:"Aseeda",origin:"Soudan",desc:"Bouillie sorgho, sauce.",tag:"Base",diff:"Facile"},
    ],
    voyage:[
      {sit:"سوق",phrase:"Bi kam?",fr:"Combien?",note:"Juba."},
      {sit:"فندق",phrase:"Fi oda fadiya?",fr:"Y a-t-il une chambre libre ?",note:"Juba Arabic pratique."},
    ],
    musique:[
      {name:"Agnwani",origin:"Sud Soudan",desc:"Chants Juba Arabic, percussions.",tag:"Tradition",diff:"Racines"},
      {name:"Nubi Tarab",origin:"Kenya",desc:"Fusion arabe-swahili, luth.",tag:"Fusion",diff:"Populaire"},
    ],
  },

  lema: {
    name:"Lema", base:"Malay-based",
    eyebrow:"Bahasa kita", title:"Belajar Kreol Melayu",
    sub:"Jakarta · Ambon · Malacca",
    btnP:"Mulai dari awal", btnS:"Saya mengerti",
    baseline:"Lema — Malay-based Creoles",
    desc:"Malay trade creoles of SE Asia.",
    speakers:"3M+", audioLbl:"Dengar kalimat", footer:"Lema adalah bahasa kita.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Belajar Kreol Melayu",
      culture:   "Budaya Lema",
      apropos:   "Siapa kita?",
      communaute:"Komunitas",
    },
    heroSubs:{
      langue:    "Jakarta · Ambon · Malacca",
      culture:   "Masakan · Musik · Perjalanan",
      apropos:   "Semua kreol dunia, satu platform",
      communaute:"Jurnal · Buku Tamu",
    },
    creoles:[
      {iso:"bew",name:"Betawi",full:"Jakarta", btnP:"Mulai dari awal", btnS:"Saya mengerti"},
      {iso:"abs",name:"Ambon",full:"Maluku", btnP:"Mulai dari awal", btnS:"Saya mengerti"},
      {iso:"mcm",name:"Kristang",full:"Malacca", btnP:"Mulai dari awal", btnS:"Saya mengerti"},
    ],
    langue:[
      {tag:"Salam",phrase:"Apa kabar lu?",fr:"Ça va?",iso:"bew",q:"Apa =",opts:["Qui","Quoi/Comment","Où"],ans:1},
    ],
    cuisine:[
      {name:"Nasi Uduk",origin:"Betawi",desc:"Riz coco, échalotes frites.",tag:"Street",diff:"Facile"},
      {name:"Ikan Asar",origin:"Ambon",desc:"Poisson fumé, spécialité des Moluques.",tag:"Plat",diff:"Moyen"},
    ],
    voyage:[
      {sit:"Pasar",phrase:"Berapa?",fr:"Combien?",note:"Jakarta."},
      {sit:"Jalan",phrase:"Di mane itu?",fr:"Où est-ce?",note:"Betawi informel."},
    ],
    musique:[
      {name:"Keroncong",origin:"Betawi",desc:"Héritage portugais, ukulélé.",tag:"Jakarta",diff:"Classique"},
      {name:"Dangdut",origin:"Indonesia",desc:"Malais + indien + arabe.",tag:"Pop",diff:"Dansant"},
      {name:"Jingkli Nona",origin:"Kristang",desc:"Chant créole portugais malais.",tag:"Malacca",diff:"Patrimoine"},
    ],
  },
};

export const APROPOS_CONTENT = {
  fr: {
    title: "Qu'est-ce que Krēolia ?",
    intro: "Krēolia est une plateforme d'apprentissage dédiée aux langues et cultures créoles du monde entier.",
    sections: [
      {
        heading: "Les langues créoles",
        text: "Une langue créole est une langue naturelle qui s'est développée à partir d'un contact prolongé entre plusieurs langues. Contrairement aux pidgins (langues de contact simplifiées), les créoles sont des langues maternelles complètes avec une grammaire riche et une littérature vivante.",
      },
      {
        heading: "Notre approche",
        text: "Krēolia s'inspire du modèle universitaire de l'INALCO : apprendre une langue, c'est aussi apprendre une culture.",
      },
      {
        heading: "7 familles, 27+ créoles",
        text: "De la Caraïbe à l'océan Indien, de l'Afrique de l'Est à l'Asie du Sud-Est : Krēolia couvre aujourd'hui plus de 27 variétés créoles regroupées en 7 grandes familles linguistiques.",
      },
    ],
    stats: [
      {val:"27+", lbl:"créoles couverts"},
      {val:"12M+", lbl:"locuteurs représentés"},
      {val:"7", lbl:"familles linguistiques"},
      {val:"4", lbl:"thématiques d'apprentissage"},
    ],
  },
  en: {
    title: "What is Krēolia?",
    intro: "Krēolia is a learning platform dedicated to creole languages and cultures worldwide.",
    sections: [
      {
        heading: "Creole languages",
        text: "A creole language is a natural language that developed from prolonged contact between several languages.",
      },
      {
        heading: "Our approach",
        text: "Krēolia is inspired by the INALCO university model: learning a language also means learning a culture.",
      },
      {
        heading: "7 families, 27+ creoles",
        text: "From the Caribbean to the Indian Ocean: Krēolia currently covers over 27 creole varieties.",
      },
    ],
    stats: [
      {val:"27+", lbl:"creoles covered"},
      {val:"12M+", lbl:"speakers represented"},
      {val:"7", lbl:"language families"},
      {val:"4", lbl:"learning themes"},
    ],
  },
  es: {
    title: "¿Qué es Krēolia?",
    intro: "Krēolia es una plataforma de aprendizaje dedicada a las lenguas y culturas criollas de todo el mundo.",
    sections: [
      {heading:"Las lenguas criollas", text:"Una lengua criolla es una lengua natural que se desarrolló a partir del contacto prolongado entre varios idiomas."},
      {heading:"Nuestro enfoque", text:"Krēolia se inspira en el modelo universitario del INALCO: aprender una lengua es también aprender una cultura."},
      {heading:"7 familias, 27+ criollos", text:"Del Caribe al Océano Índico: Krēolia cubre más de 27 variedades criollas agrupadas en 7 grandes familias lingüísticas."},
    ],
    stats:[{val:"27+",lbl:"criollos"},{val:"12M+",lbl:"hablantes"},{val:"7",lbl:"familias"},{val:"4",lbl:"temáticas"}],
  },
  pt: {
    title: "O que é Krēolia?",
    intro: "Krēolia é uma plataforma de aprendizagem dedicada às línguas e culturas crioulas de todo o mundo.",
    sections: [
      {heading:"As línguas crioulas", text:"Uma língua crioula é uma língua natural que se desenvolveu a partir do contato prolongado entre várias línguas."},
      {heading:"A nossa abordagem", text:"Krēolia inspira-se no modelo universitário do INALCO: aprender uma língua é também aprender uma cultura."},
      {heading:"7 famílias, 27+ crioulos", text:"Do Caribe ao Oceano Índico: Krēolia cobre mais de 27 variedades crioulas agrupadas em 7 grandes famílias linguísticas."},
    ],
    stats:[{val:"27+",lbl:"crioulos"},{val:"12M+",lbl:"falantes"},{val:"7",lbl:"famílias"},{val:"4",lbl:"temáticas"}],
  },
  nl: {
    title: "Wat is Krēolia?",
    intro: "Krēolia is een leerplatform gewijd aan creoolse talen en culturen wereldwijd.",
    sections: [
      {heading:"Creoolse talen", text:"Een creoolse taal is een natuurlijke taal die zich ontwikkelde uit langdurig contact tussen meerdere talen."},
      {heading:"Onze aanpak", text:"Krēolia is geïnspireerd op het universitaire model van het INALCO: een taal leren betekent ook een cultuur leren."},
      {heading:"7 families, 27+ creolen", text:"Van de Caraïben tot de Indische Oceaan: Krēolia dekt meer dan 27 creoolse variëteiten in 7 grote taalfamilies."},
    ],
    stats:[{val:"27+",lbl:"creolen"},{val:"12M+",lbl:"sprekers"},{val:"7",lbl:"families"},{val:"4",lbl:"thema's"}],
  },
  ar: {
    title: "ما هو Krēolia؟",
    intro: "Krēolia منصة تعليمية مخصصة للغات والثقافات الكريولية حول العالم.",
    sections: [
      {heading:"اللغات الكريولية", text:"اللغة الكريولية هي لغة طبيعية نشأت من تلاقي عدة لغات لفترة طويلة."},
      {heading:"نهجنا", text:"تستلهم Krēolia من النموذج الجامعي لمعهد INALCO: تعلم لغة يعني أيضاً تعلم ثقافة."},
      {heading:"٧ عائلات، أكثر من ٢٧ كريولية", text:"من البحر الكاريبي إلى المحيط الهندي: تغطي Krēolia أكثر من ٢٧ صنفاً كريولياً."},
    ],
    stats:[{val:"٢٧+",lbl:"كريول"},{val:"١٢م+",lbl:"متحدث"},{val:"٧",lbl:"عائلات"},{val:"٤",lbl:"موضوعات"}],
  },
  ms: {
    title: "Apa itu Krēolia?",
    intro: "Krēolia ialah platform pembelajaran yang didedikasikan untuk bahasa dan budaya kreol di seluruh dunia.",
    sections: [
      {heading:"Bahasa kreol", text:"Bahasa kreol ialah bahasa semula jadi yang berkembang daripada hubungan berpanjangan antara beberapa bahasa."},
      {heading:"Pendekatan kami", text:"Krēolia terinspirasi oleh model universiti INALCO: mempelajari bahasa bermakna juga mempelajari budaya."},
      {heading:"7 keluarga, 27+ kreol", text:"Dari Caribbean ke Lautan Hindi: Krēolia merangkumi lebih 27 varieti kreol dalam 7 keluarga linguistik utama."},
    ],
    stats:[{val:"27+",lbl:"kreol"},{val:"12J+",lbl:"penutur"},{val:"7",lbl:"keluarga"},{val:"4",lbl:"tema"}],
  },
};

export const UI_LABELS = {
  fr:{
    langue:"Langue", culture:"Culture", apropos:"À propos", communaute:"Communauté",
    cultureSubTabs:{ voyage:"Voyage", cuisine:"Cuisine", musique:"Musique" },
    chipLabel:"Famille créole à base de",
    searchPlaceholder:"Rechercher une leçon, un mot, un plat…",
    searchPlaceholderCulture:"Rechercher une recette, un rythme, une destination…",
    lessonCount:(n)=>`${n} leçon${n!==1?'s':''}`,
    recipeCount:(n)=>`${n} recette${n!==1?'s':''}`,
    expressionCount:(n)=>`${n} expression${n!==1?'s':''}`,
    styleCount:(n)=>`${n} style${n!==1?'s':''}`,
    sectionTitles:{ langue:"Leçons de langue", cuisine:"Cuisine créole", voyage:"Expressions de voyage", musique:"Musiques créoles", apropos:"À propos de Krēolia", communaute:"Journal de bord" },
    heroBtnP_langue:"Commencer depuis zéro",
    heroBtnS_langue:"Je comprends déjà",
    heroBtnP_culture:"Explorer la culture",
    heroBtnS_culture:"Voir tout",
    heroBtnP_apropos:"Découvrir Krēolia",
    heroBtnS_apropos:"Les familles créoles",
    heroBtnP_communaute:"Lire le journal",
    heroBtnS_communaute:"Laisser un message",
    communautePostBtn:"Publier",
    communautePostPlaceholder:"Partagez une pensée, une question, une découverte…",
    communauteLoginPrompt:"Connectez-vous pour publier un message.",
    loginBtn:"Connexion",
    logoutBtn:"✕ Déco",
    loginTitle:"Connexion",
    registerTitle:"Inscription",
    loginSubmit:"Se connecter",
    registerSubmit:"Créer mon compte",
    loginSwitch:"Pas encore de compte ?",
    loginSwitchLink:"S'inscrire",
    registerSwitch:"Déjà un compte ?",
    registerSwitchLink:"Se connecter",
    fieldEmail:"E-mail",
    fieldPassword:"Mot de passe",
    fieldPseudo:"Pseudo",
    fieldPasswordHint:"(min. 6 caractères)",
    footerFamilies:"Familles créoles",
    footerNav:"Navigation",
    footerTaglineSuffix:"Toutes les langues et cultures créoles, une seule plateforme.",
    bases:{"FR-based":"francés","EN-based":"anglais","PT-based":"portugais","ES-based":"espagnol","NL-based":"néerlandais","AR-based":"arabe","Malay-based":"malais"},
    v2label:"(v2)",
    comingSoon:"Bientôt disponible",
    noLesson:"Aucune leçon trouvée.",
    noContent:"Contenu bientôt disponible.",
  },
  en:{
    langue:"Language", culture:"Culture", apropos:"About", communaute:"Community",
    cultureSubTabs:{ voyage:"Travel", cuisine:"Food", musique:"Music" },
    chipLabel:"Creole family based on",
    searchPlaceholder:"Search a lesson, a word, a dish…",
    searchPlaceholderCulture:"Search a recipe, a rhythm, a destination…",
    lessonCount:(n)=>`${n} lesson${n!==1?'s':''}`,
    recipeCount:(n)=>`${n} recipe${n!==1?'s':''}`,
    expressionCount:(n)=>`${n} expression${n!==1?'s':''}`,
    styleCount:(n)=>`${n} style${n!==1?'s':''}`,
    sectionTitles:{ langue:"Language lessons", cuisine:"Creole cuisine", voyage:"Travel expressions", musique:"Creole music", apropos:"About Krēolia", communaute:"Guestbook" },
    heroBtnP_langue:"Start from scratch",
    heroBtnS_langue:"I already understand",
    heroBtnP_culture:"Explore culture",
    heroBtnS_culture:"See all",
    heroBtnP_apropos:"Discover Krēolia",
    heroBtnS_apropos:"Creole families",
    heroBtnP_communaute:"Read the journal",
    heroBtnS_communaute:"Leave a message",
    communautePostBtn:"Post",
    communautePostPlaceholder:"Share a thought, a question, a discovery…",
    communauteLoginPrompt:"Log in to post a message.",
    loginBtn:"Log in",
    logoutBtn:"✕ Log out",
    loginTitle:"Log in",
    registerTitle:"Sign up",
    loginSubmit:"Log in",
    registerSubmit:"Create account",
    loginSwitch:"No account yet?",
    loginSwitchLink:"Sign up",
    registerSwitch:"Already have an account?",
    registerSwitchLink:"Log in",
    fieldEmail:"Email",
    fieldPassword:"Password",
    fieldPseudo:"Username",
    fieldPasswordHint:"(min. 6 characters)",
    footerFamilies:"Creole families",
    footerNav:"Navigation",
    footerTaglineSuffix:"All the world's creoles, one platform.",
    bases:{"FR-based":"French","EN-based":"English","PT-based":"Portuguese","ES-based":"Spanish","NL-based":"Dutch","AR-based":"Arabic","Malay-based":"Malay"},
    v2label:"(v2)",
    comingSoon:"Coming soon",
    noLesson:"No lesson found.",
    noContent:"Content coming soon.",
  },
};

export const UI_LANGUAGES = [
  {code:"fr", label:"FR", v2:false},
  {code:"en", label:"EN", v2:false},
];
