/* ============================================================
   DATA — familles créoles + UI labels i18n
   ============================================================ */

export const FAMILIES = {
  kilti: {
    name:"Kilti", nameClass:"", base:"FR-based",
    eyebrow:"Lang péyi nou", title:"Aprann Kréyòl",
    sub:"Guadeloupe · Martinique · Réunion · Maurice · Louisiane · Haïti",
    btnP:"Kòmansé dèpi zéro", btnS:"Mwen ja ka konpwann",
    baseline:"Aprann kréyòl — Learn Creole",
    desc:"French-based creoles are spoken by over 12 million people. Born from French with African, Amerindian and Malagasy substrata.",
    speakers:"12M+", audioLbl:"Tann fraz-la", footer:"Kréyòl sé lang nou.",
    /* Hero visuels par onglet */
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    /* Titres hero par onglet (clé = tab) */
    heroTitles:{
      langue:    "Aprann Kréyòl",
      culture:   "Kilti Kréyòl",
      apropos:   "Ki nou yé ?",
      communaute:"Ansanm nou fò",
    },
    heroSubs:{
      langue:    "Guadeloupe · Martinique · Réunion · Maurice · Louisiane · Haïti",
      culture:   "Cuisine · Musique · Voyage",
      apropos:   "La plateforme de toutes les languesv et cultures créoles",
      communaute:"Journal de bord · Livre d'or",
    },
    creoles:[
      {iso:"gcf",name:"Gwadloupéyen",full:"Kréyòl Gwadloup"},
      {iso:"gcf",name:"Matiniké",full:"Kréyòl Matnik"},
      {iso:"hat",name:"Haïtien",full:"Kreyòl ayisyen"},
      {iso:"rcf",name:"Réyoné",full:"Kréol réinioné"},
      {iso:"mfe",name:"Morisyen",full:"Kreol Morisyen"},
      {iso:"lou",name:"Lwizyannais",full:"Kréyòl Lwizyàn"},
    ],
    langue:[
      {tag:"Salitasyon",phrase:"Bonjou, kijan ou yé ?",fr:"Bonjour, comment vas-tu ?",iso:"gcf",q:"Que signifie « kijan ou yé ? »",opts:["Comment tu t'appelles ?","Comment vas-tu ?","Où vas-tu ?"],ans:1},
      {tag:"Manjé",phrase:"An vlé on bokit.",fr:"Je veux un bokit.",iso:"gcf",q:"Le bokit est :",opts:["Une boisson","Un sandwich frit","Un dessert"],ans:1},
      {tag:"Tan",phrase:"I ka fè chò.",fr:"Il fait chaud.",iso:"gcf",q:"« chò » =",opts:["Froid","Chaud","Pluie"],ans:1},
    ],
    cuisine:[
      {name:"Bokit",origin:"Guadeloupe · gcf",desc:"Pain frit garnis, street-food n°1.",tag:"Snack",diff:"Facile"},
      {name:"Colombo",origin:"Martinique · gcf",desc:"Cari aux épices indiennes, poulet ou cabri.",tag:"Plat",diff:"Moyen"},
      {name:"Accras de morue",origin:"Antilles · gcf",desc:"Beignets de morue épicés, apéritif incontournable.",tag:"Apéro",diff:"Facile"},
    ],
    voyage:[
      {sit:"Aéroport",phrase:"Kote toilet-la yé ?",fr:"Où sont les toilettes ?",note:"Indispensable à l'arrivée."},
      {sit:"Marché",phrase:"Sa ka kouté ?",fr:"Combien ça coûte ?",note:"Marchandage amical."},
      {sit:"Taxi",phrase:"Mennen mwen la, souplé.",fr:"Emmenez-moi là-bas, s'il vous plaît.",note:"Poli et efficace."},
    ],
    musique:[
      {name:"Zouk",origin:"Guadeloupe/Martinique",desc:"Né avec Kassav' (1980s). Fusion cadence, funk, compas.",tag:"Danse",diff:"Iconique"},
      {name:"Gwo Ka",origin:"Guadeloupe",desc:"7 rythmes, tambour ka, chant répondè. UNESCO.",tag:"Patrimoine",diff:"Racines"},
      {name:"Bèlè",origin:"Martinique",desc:"Tambour et ti-bwa, danse de lutte.",tag:"Tradition",diff:"Rituel"},
      {name:"Sega",origin:"Maurice/Réunion",desc:"Ravanne, triangle, chant créole océan Indien.",tag:"Océan Indien",diff:"Populaire"},
      {name:"Compas",origin:"Haïti",desc:"Créé par Nemours Jean-Baptiste, base du konpa moderne.",tag:"Haïti",diff:"Incontournable"},
    ],
  },

  kalcha: {
    name:"Kalcha", base:"EN-based",
    eyebrow:"Island tongue", title:"Learn Creole English",
    sub:"Jamaica · Trinidad · Belize · Nigeria",
    btnP:"Start from scratch", btnS:"I already understand",
    baseline:"Kalcha — English-based Creoles",
    desc:"English-based creoles across Caribbean, Africa and Pacific.",
    speakers:"8M+", audioLbl:"Listen phrase", footer:"Kalcha is our voice.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Learn Creole English",
      culture:   "Kalcha Culture",
      apropos:   "Who we are",
      communaute:"Community",
    },
    heroSubs:{
      langue:    "Jamaica · Trinidad · Belize · Nigeria",
      culture:   "Food · Music · Travel",
      apropos:   "All the world's creoles, one platform",
      communaute:"Guestbook · Journal",
    },
    creoles:[
      {iso:"jam",name:"Jamaican",full:"Patois"},
      {iso:"trf",name:"Trinidadian",full:"Trini Creole"},
      {iso:"pcm",name:"Nigerian",full:"Naija Pidgin"},
    ],
    langue:[
      {tag:"Greeting",phrase:"Wah gwaan?",fr:"What's up?",iso:"jam",q:"Meaning?",opts:["Goodbye","What's up?","Thanks"],ans:1},
    ],
    cuisine:[
      {name:"Jerk Chicken",origin:"Jamaica",desc:"Scotch bonnet, pimento, slow smoke.",tag:"Grill",diff:"Hard"},
      {name:"Doubles",origin:"Trinidad",desc:"Bara bread, channa curry, pepper sauce.",tag:"Street",diff:"Easy"},
    ],
    voyage:[
      {sit:"Airport",phrase:"How much fi di taxi?",fr:"How much for the taxi?",note:"Always ask before entering."},
      {sit:"Market",phrase:"How much fi dis?",fr:"How much is this?",note:"Universal haggling."},
    ],
    musique:[
      {name:"Reggae",origin:"Jamaica",desc:"Heavy bass, social message. Bob Marley.",tag:"World",diff:"Legend"},
      {name:"Dancehall",origin:"Jamaica",desc:"Sound systems, digital riddims.",tag:"Urban",diff:"Energy"},
      {name:"Calypso",origin:"Trinidad",desc:"Carnival satire, steelpan.",tag:"Carnival",diff:"Roots"},
      {name:"Soca",origin:"Trinidad",desc:"Soul+Calypso, king of carnival.",tag:"Party",diff:"Popular"},
      {name:"Afrobeats Pidgin",origin:"Nigeria",desc:"Naija pidgin on afro beats.",tag:"Africa",diff:"Modern"},
    ],
  },

  'kultura-pt': {
    name:"Kultura", nameClass:"", base:"PT-based",
    eyebrow:"Língua do povo", title:"Aprende o Crioulo",
    sub:"Cabo Verde · Guiné-Bissau · Malacca",
    btnP:"Kumesa di zero", btnS:"N dja papia",
    baseline:"Kultura PT — Portuguese-based Creoles",
    desc:"Portuguese-based creoles across Atlantic and Indian Ocean routes.",
    speakers:"2M+", audioLbl:"Uvi frazi", footer:"Kultura PT é nha raiz.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Aprende o Crioulo",
      culture:   "Kultura Criola",
      apropos:   "Kén nu é?",
      communaute:"Komunidade",
    },
    heroSubs:{
      langue:    "Cabo Verde · Guiné-Bissau · Malacca",
      culture:   "Kuzinha · Múzika · Viaji",
      apropos:   "Tudu kriol di mundu, un plataforma",
      communaute:"Diáriu · Livru d'oru",
    },
    creoles:[
      {iso:"kea",name:"Kabuverdianu",full:"Cabo Verde"},
      {iso:"pov",name:"Guinéense",full:"Guinea-Bissau"},
      {iso:"mcm",name:"Kristang",full:"Malacca"},
    ],
    langue:[
      {tag:"Saudação",phrase:"Modi bu sta?",fr:"Comment vas-tu?",iso:"kea",q:"Modi =",opts:["Où","Comment","Quand"],ans:1},
      {tag:"Mercado",phrase:"I sta dretu.",fr:"Je vais bien.",iso:"pov",q:"« dretu » veut dire:",opts:["bien","vite","loin"],ans:0},
      {tag:"Casa",phrase:"Bos teng fome?",fr:"Tu as faim?",iso:"mcm",q:"« fome » =",opts:["soif","faim","sommeil"],ans:1},
    ],
    cuisine:[
      {name:"Kachupa",origin:"Cabo Verde",desc:"Ragoût maïs/haricots, plat national.",tag:"Plat",diff:"Moyen"},
    ],
    voyage:[
      {sit:"Mercado",phrase:"Kantu ki e?",fr:"Combien?",note:"Cap-Vert."},
      {sit:"Rua",phrase:"Undi ki bu ta bai?",fr:"Où vas-tu?",note:"Salutation informelle."},
    ],
    musique:[
      {name:"Morna",origin:"Cabo Verde",desc:"Cesária Évora. Saudade créole.",tag:"UNESCO",diff:"Âme"},
      {name:"Funaná",origin:"Cabo Verde",desc:"Accordéon, ferrinho. Rythme paysan.",tag:"Danse",diff:"Rapide"},
      {name:"Jingkli Nona",origin:"Malacca",desc:"Chant kristang d'origine luso-asiatique.",tag:"Patrimoine",diff:"Rare"},
    ],
  },

  'kultura-es': {
    name:"Kultura", nameClass:"", base:"ES-based",
    eyebrow:"Lengua del pueblo", title:"Aprende el Criollo",
    sub:"Caribe hispano · Chabacano · Papiamentu",
    btnP:"Empieza desde cero", btnS:"Ya entiendo",
    baseline:"Kultura ES — Spanish-based Creoles",
    desc:"Spanish-based creoles and Iberian-contact varieties.",
    speakers:"1M+", audioLbl:"Escucha frase", footer:"Kultura ES es nuestra voz.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Aprende el Criollo",
      culture:   "Kultura Criolla",
      apropos:   "¿Quiénes somos?",
      communaute:"Comunidad",
    },
    heroSubs:{
      langue:    "Caribe hispano · Chabacano · Papiamentu",
      culture:   "Cocina · Música · Viaje",
      apropos:   "Todos los criollos del mundo, una plataforma",
      communaute:"Diario · Libro de visitas",
    },
    creoles:[
      {iso:"ckz",name:"Chabacano",full:"Zamboanga"},
      {iso:"pap",name:"Papiamentu",full:"ABC Islands"},
    ],
    langue:[
      {tag:"Saludo",phrase:"Kosa ta pasa?",fr:"Que se passe-t-il ?",iso:"pap",q:"« Kosa ta pasa » =",opts:["Comment ça va","D'où viens-tu","À bientôt"],ans:0},
      {tag:"Calle",phrase:"Onde tu anda?",fr:"Où vas-tu ?",iso:"ckz",q:"« onde » signifie:",opts:["où","pourquoi","quand"],ans:0},
    ],
    cuisine:[
      {name:"Sancocho criollo",origin:"Caribe hispano",desc:"Ragoût rustique, légumes et viande.",tag:"Plat",diff:"Moyen"},
    ],
    voyage:[
      {sit:"Barrio",phrase:"Kuanto ese?",fr:"Combien ça coûte ?",note:"Usage courant."},
      {sit:"Playa",phrase:"Unda bo ta bai?",fr:"Où vas-tu?",note:"Papiamentu informel."},
    ],
    musique:[
      {name:"Tumba",origin:"Curaçao",desc:"Rythme de carnaval en papiamentu.",tag:"Carnaval",diff:"Festif"},
      {name:"Chabacano Pop",origin:"Zamboanga",desc:"Pop locale avec refrains créoles hispaniques.",tag:"Urbain",diff:"Moderne"},
    ],
  },

  'kultura-nl': {
    name:"Kultura", nameClass:"", base:"NL-based",
    eyebrow:"Taal van het volk", title:"Leer Creools",
    sub:"Dutch-contact · Caribbean · Guyana",
    btnP:"Begin vanaf nul", btnS:"Ik begrijp al",
    baseline:"Kultura NL — Dutch-based Creoles",
    desc:"Dutch-based and Dutch-contact creoles from Atlantic history.",
    speakers:"0.5M+", audioLbl:"Luister zin", footer:"Kultura NL leeft voort.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Leer Creools",
      culture:   "Creoolse Cultuur",
      apropos:   "Wie zijn wij?",
      communaute:"Gemeenschap",
    },
    heroSubs:{
      langue:    "Dutch-contact · Caribbean · Guyana",
      culture:   "Keuken · Muziek · Reizen",
      apropos:   "Alle creoolse talen, één platform",
      communaute:"Dagboek · Gastenboek",
    },
    creoles:[
      {iso:"skw",name:"Skepi",full:"Guyana"},
      {iso:"brc",name:"Berbice",full:"Guyana"},
    ],
    langue:[
      {tag:"Groet",phrase:"Fa yu de?",fr:"Comment vas-tu ?",iso:"skw",q:"« Fa » signifie:",opts:["comment","demain","encore"],ans:0},
      {tag:"Markt",phrase:"Mi wani bai na winkel.",fr:"Je veux aller au magasin.",iso:"brc",q:"« wani » =",opts:["vouloir","devoir","savoir"],ans:0},
    ],
    cuisine:[
      {name:"Pastechi creool",origin:"Dutch Caribbean",desc:"Petits chaussons frits, version locale.",tag:"Snack",diff:"Facile"},
    ],
    voyage:[
      {sit:"Straat",phrase:"Fa yu de tide?",fr:"Comment vas-tu aujourd'hui ?",note:"Formule amicale."},
      {sit:"Winkel",phrase:"Wan prijs?",fr:"Quel prix ?",note:"Direct et efficace."},
    ],
    musique:[
      {name:"Tambú",origin:"Curaçao",desc:"Percussions profondes et chant responsorial.",tag:"Racines",diff:"Intense"},
      {name:"Kaseko",origin:"Suriname",desc:"Fanfare créole, groove dansant.",tag:"Danse",diff:"Classique"},
    ],
  },

  takafa: {
    name:"تكافا", nameClass:"logo-ar", base:"AR-based",
    eyebrow:"لغة الشعب", title:"تعلم العربية الكريولية", titleClass:"title-ar",
    sub:"Juba · Nubi · Soudan",
    btnP:"ابدأ من الصفر", btnS:"أنا أفهم",
    baseline:"تكافا — Creoles arabes",
    desc:"Arabic-based pidgins of East Africa.",
    speakers:"2M+", audioLbl:"استمع للجملة", footer:".تكافا هي جذورنا",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "تعلم العربية الكريولية",
      culture:   "ثقافة تكافا",
      apropos:   "من نحن؟",
      communaute:"المجتمع",
    },
    heroSubs:{
      langue:    "Juba · Nubi · Soudan",
      culture:   "مطبخ · موسيقى · سفر",
      apropos:   "كل الكريول في العالم، منصة واحدة",
      communaute:"مذكرات · سجل الزوار",
    },
    creoles:[
      {iso:"pga",name:"Juba",full:"Juba Arabic"},
      {iso:"nub",name:"Nubi",full:"Kenya/Uganda"},
    ],
    langue:[
      {tag:"تحية",phrase:"Keif halak?",fr:"Comment vas-tu?",iso:"pga",q:"معنى",opts:["مرحبا","كيف حالك","شكرا"],ans:1},
    ],
    cuisine:[
      {name:"Aseeda",origin:"Soudan",desc:"Bouillie sorgho, sauce.",tag:"Base",diff:"Facile"},
    ],
    voyage:[
      {sit:"سوق",phrase:"Bi kam?",fr:"Combien?",note:"Juba."},
      {sit:"فندق",phrase:"Fi oda fadiya?",fr:"Y a-t-il une chambre libre ?",note:"Juba Arabic pratique."},
    ],
    musique:[
      {name:"Agnwani",origin:"Sud Soudan",desc:"Chants Juba Arabic, percussions.",tag:"Tradition",diff:"Racines"},
      {name:"Nubi Tarab",origin:"Kenya",desc:"Fusion arabe-swahili, luth.",tag:"Fusion",diff:"Populaire"},
    ],
  },

  lema: {
    name:"Lema", base:"Malay-based",
    eyebrow:"Bahasa kita", title:"Belajar Kreol Melayu",
    sub:"Jakarta · Ambon · Malacca",
    btnP:"Mulai dari awal", btnS:"Saya mengerti",
    baseline:"Lema — Malay-based Creoles",
    desc:"Malay trade creoles of SE Asia.",
    speakers:"3M+", audioLbl:"Dengar kalimat", footer:"Lema adalah bahasa kita.",
    heroImages:{
      langue:  ['assets/images/hero-visual.jpg','assets/images/hero-visual-2.jpg','assets/images/hero-visual-3.jpg'],
      culture: ['assets/images/hero-cuisine.jpg','assets/images/hero-musique.jpg','assets/images/hero-voyage.jpg'],
      apropos: ['assets/images/hero-visual.jpg'],
      communaute: ['assets/images/hero-visual-2.jpg'],
    },
    heroTitles:{
      langue:    "Belajar Kreol Melayu",
      culture:   "Budaya Lema",
      apropos:   "Siapa kita?",
      communaute:"Komunitas",
    },
    heroSubs:{
      langue:    "Jakarta · Ambon · Malacca",
      culture:   "Masakan · Musik · Perjalanan",
      apropos:   "Semua kreol dunia, satu platform",
      communaute:"Jurnal · Buku Tamu",
    },
    creoles:[
      {iso:"bew",name:"Betawi",full:"Jakarta"},
      {iso:"abs",name:"Ambon",full:"Maluku"},
      {iso:"mcm",name:"Kristang",full:"Malacca"},
    ],
    langue:[
      {tag:"Salam",phrase:"Apa kabar lu?",fr:"Ça va?",iso:"bew",q:"Apa =",opts:["Qui","Quoi/Comment","Où"],ans:1},
    ],
    cuisine:[
      {name:"Nasi Uduk",origin:"Betawi",desc:"Riz coco, échalotes frites.",tag:"Street",diff:"Facile"},
      {name:"Ikan Asar",origin:"Ambon",desc:"Poisson fumé, spécialité des Moluques.",tag:"Plat",diff:"Moyen"},
    ],
    voyage:[
      {sit:"Pasar",phrase:"Berapa?",fr:"Combien?",note:"Jakarta."},
      {sit:"Jalan",phrase:"Di mane itu?",fr:"Où est-ce?",note:"Betawi informel."},
    ],
    musique:[
      {name:"Keroncong",origin:"Betawi",desc:"Héritage portugais, ukulélé.",tag:"Jakarta",diff:"Classique"},
      {name:"Dangdut",origin:"Indonesia",desc:"Malais + indien + arabe.",tag:"Pop",diff:"Dansant"},
      {name:"Jingkli Nona",origin:"Kristang",desc:"Chant créole portugais malais.",tag:"Malacca",diff:"Patrimoine"},
    ],
  },
};

/* ============================================================
   À PROPOS — contenu statique (commun à toutes les familles)
   ============================================================ */
export const APROPOS_CONTENT = {
  fr: {
    title: "Qu'est-ce que Krēolia ?",
    intro: "Krēolia est une plateforme d'apprentissage dédiée aux langues et cultures créoles du monde entier. Né d'une passion pour la diversité linguistique, ce projet réunit en un seul endroit les familles créoles à base française, anglaise, portugaise, espagnole, néerlandaise, arabe et malaise.",
    sections: [
      {
        heading: "Les langues créoles",
        text: "Une langue créole est une langue naturelle qui s'est développée à partir d'un contact prolongé entre plusieurs langues. Contrairement aux pidgins (langues de contact simplifiées), les créoles sont des langues maternelles complètes avec une grammaire riche et une littérature vivante.",
      },
      {
        heading: "Notre approche",
        text: "Krēolia s'inspire du modèle universitaire de l'INALCO (Institut National des Langues et Civilisations Orientales) : apprendre une langue, c'est aussi apprendre une culture — sa cuisine, sa musique, ses voyages, son histoire.",
      },
      {
        heading: "7 familles, 27+ créoles",
        text: "De la Caraïbe à l'océan Indien, de l'Afrique de l'Est à l'Asie du Sud-Est : Krēolia couvre aujourd'hui plus de 27 variétés créoles regroupées en 7 grandes familles linguistiques.",
      },
    ],
    stats: [
      {val:"27+", lbl:"créoles couverts"},
      {val:"12M+", lbl:"locuteurs représentés"},
      {val:"7", lbl:"familles linguistiques"},
      {val:"4", lbl:"thématiques d'apprentissage"},
    ],
  },
  en: {
    title: "What is Krēolia?",
    intro: "Krēolia is a learning platform dedicated to creole languages and cultures worldwide. Born from a passion for linguistic diversity, this project brings together French, English, Portuguese, Spanish, Dutch, Arabic and Malay-based creole families in one place.",
    sections: [
      {
        heading: "Creole languages",
        text: "A creole language is a natural language that developed from prolonged contact between several languages. Unlike pidgins (simplified contact languages), creoles are complete mother tongues with rich grammar and vibrant literature.",
      },
      {
        heading: "Our approach",
        text: "Krēolia is inspired by the INALCO university model: learning a language also means learning a culture — its cuisine, music, travel, and history.",
      },
      {
        heading: "7 families, 27+ creoles",
        text: "From the Caribbean to the Indian Ocean, from East Africa to Southeast Asia: Krēolia currently covers over 27 creole varieties grouped into 7 major linguistic families.",
      },
    ],
    stats: [
      {val:"27+", lbl:"creoles covered"},
      {val:"12M+", lbl:"speakers represented"},
      {val:"7", lbl:"language families"},
      {val:"4", lbl:"learning themes"},
    ],
  },
  es: {
    title: "¿Qué es Krēolia?",
    intro: "Krēolia es una plataforma de aprendizaje dedicada a las lenguas y culturas criollas de todo el mundo.",
    sections: [
      {heading:"Las lenguas criollas", text:"Una lengua criolla es una lengua natural que se desarrolló a partir del contacto prolongado entre varios idiomas."},
      {heading:"Nuestro enfoque", text:"Krēolia se inspira en el modelo universitario del INALCO: aprender una lengua es también aprender una cultura."},
      {heading:"7 familias, 27+ criollos", text:"Del Caribe al Océano Índico: Krēolia cubre más de 27 variedades criollas agrupadas en 7 grandes familias lingüísticas."},
    ],
    stats:[{val:"27+",lbl:"criollos"},{val:"12M+",lbl:"hablantes"},{val:"7",lbl:"familias"},{val:"4",lbl:"temáticas"}],
  },
  pt: {
    title: "O que é Krēolia?",
    intro: "Krēolia é uma plataforma de aprendizagem dedicada às línguas e culturas crioulas de todo o mundo.",
    sections: [
      {heading:"As línguas crioulas", text:"Uma língua crioula é uma língua natural que se desenvolveu a partir do contato prolongado entre várias línguas."},
      {heading:"A nossa abordagem", text:"Krēolia inspira-se no modelo universitário do INALCO: aprender uma língua é também aprender uma cultura."},
      {heading:"7 famílias, 27+ crioulos", text:"Do Caribe ao Oceano Índico: Krēolia cobre mais de 27 variedades crioulas agrupadas em 7 grandes famílias linguísticas."},
    ],
    stats:[{val:"27+",lbl:"crioulos"},{val:"12M+",lbl:"falantes"},{val:"7",lbl:"famílias"},{val:"4",lbl:"temáticas"}],
  },
  nl: {
    title: "Wat is Krēolia?",
    intro: "Krēolia is een leerplatform gewijd aan creoolse talen en culturen wereldwijd.",
    sections: [
      {heading:"Creoolse talen", text:"Een creoolse taal is een natuurlijke taal die zich ontwikkelde uit langdurig contact tussen meerdere talen."},
      {heading:"Onze aanpak", text:"Krēolia is geïnspireerd op het universitaire model van het INALCO: een taal leren betekent ook een cultuur leren."},
      {heading:"7 families, 27+ creolen", text:"Van de Caraïben tot de Indische Oceaan: Krēolia dekt meer dan 27 creoolse variëteiten in 7 grote taalfamilies."},
    ],
    stats:[{val:"27+",lbl:"creolen"},{val:"12M+",lbl:"sprekers"},{val:"7",lbl:"families"},{val:"4",lbl:"thema's"}],
  },
  ar: {
    title: "ما هو Krēolia؟",
    intro: "Krēolia منصة تعليمية مخصصة للغات والثقافات الكريولية حول العالم.",
    sections: [
      {heading:"اللغات الكريولية", text:"اللغة الكريولية هي لغة طبيعية نشأت من تلاقي عدة لغات لفترة طويلة."},
      {heading:"نهجنا", text:"تستلهم Krēolia من النموذج الجامعي لمعهد INALCO: تعلم لغة يعني أيضاً تعلم ثقافة."},
      {heading:"٧ عائلات، أكثر من ٢٧ كريولية", text:"من البحر الكاريبي إلى المحيط الهندي: تغطي Krēolia أكثر من ٢٧ صنفاً كريولياً."},
    ],
    stats:[{val:"٢٧+",lbl:"كريول"},{val:"١٢م+",lbl:"متحدث"},{val:"٧",lbl:"عائلات"},{val:"٤",lbl:"موضوعات"}],
  },
  ms: {
    title: "Apa itu Krēolia?",
    intro: "Krēolia ialah platform pembelajaran yang didedikasikan untuk bahasa dan budaya kreol di seluruh dunia.",
    sections: [
      {heading:"Bahasa kreol", text:"Bahasa kreol ialah bahasa semula jadi yang berkembang daripada hubungan berpanjangan antara beberapa bahasa."},
      {heading:"Pendekatan kami", text:"Krēolia terinspirasi oleh model universiti INALCO: mempelajari bahasa bermakna juga mempelajari budaya."},
      {heading:"7 keluarga, 27+ kreol", text:"Dari Caribbean ke Lautan Hindi: Krēolia merangkumi lebih 27 varieti kreol dalam 7 keluarga linguistik utama."},
    ],
    stats:[{val:"27+",lbl:"kreol"},{val:"12J+",lbl:"penutur"},{val:"7",lbl:"keluarga"},{val:"4",lbl:"tema"}],
  },
};

/* ============================================================
   UI LABELS — i18n complet
   ============================================================ */
export const UI_LABELS = {
  fr:{
    langue:"Langue", culture:"Culture", apropos:"À propos", communaute:"Communauté",
    cultureSubTabs:{ voyage:"Voyage", cuisine:"Cuisine", musique:"Musique" },
    chipLabel:"Famille créole à base de",
    searchPlaceholder:"Rechercher une leçon, un mot, un plat…",
    searchPlaceholderCulture:"Rechercher une recette, un rythme, une destination…",
    lessonCount:(n)=>`${n} leçon${n!==1?'s':''}`,
    recipeCount:(n)=>`${n} recette${n!==1?'s':''}`,
    expressionCount:(n)=>`${n} expression${n!==1?'s':''}`,
    styleCount:(n)=>`${n} style${n!==1?'s':''}`,
    sectionTitles:{ langue:"Leçons de langue", cuisine:"Cuisine créole", voyage:"Expressions de voyage", musique:"Musiques créoles", apropos:"À propos de Krēolia", communaute:"Journal de bord" },
    heroBtnP_langue:"Commencer depuis zéro",
    heroBtnS_langue:"Je comprends déjà",
    heroBtnP_culture:"Explorer la culture",
    heroBtnS_culture:"Voir tout",
    heroBtnP_apropos:"Découvrir Krēolia",
    heroBtnS_apropos:"Les familles créoles",
    heroBtnP_communaute:"Lire le journal",
    heroBtnS_communaute:"Laisser un message",
    communautePostBtn:"Publier",
    communautePostPlaceholder:"Partagez une pensée, une question, une découverte…",
    communauteLoginPrompt:"Connectez-vous pour publier un message.",
    loginBtn:"Connexion",
    logoutBtn:"✕ Déco",
    loginTitle:"Connexion",
    registerTitle:"Inscription",
    loginSubmit:"Se connecter",
    registerSubmit:"Créer mon compte",
    loginSwitch:"Pas encore de compte ?",
    loginSwitchLink:"S'inscrire",
    registerSwitch:"Déjà un compte ?",
    registerSwitchLink:"Se connecter",
    fieldEmail:"E-mail",
    fieldPassword:"Mot de passe",
    fieldPseudo:"Pseudo",
    fieldPasswordHint:"(min. 6 caractères)",
    footerFamilies:"Familles créoles",
    footerNav:"Navigation",
    footerTaglineSuffix:"Toutes les langues et cultures créoles, une seule plateforme.",
    bases:{"FR-based":"français","EN-based":"anglais","PT-based":"portugais","ES-based":"espagnol","NL-based":"néerlandais","AR-based":"arabe","Malay-based":"malais"},
    v2label:"(v2)",
    comingSoon:"Bientôt disponible",
    noLesson:"Aucune leçon trouvée.",
    noContent:"Contenu bientôt disponible.",
  },
  en:{
    langue:"Language", culture:"Culture", apropos:"About", communaute:"Community",
    cultureSubTabs:{ voyage:"Travel", cuisine:"Food", musique:"Music" },
    chipLabel:"Creole family based on",
    searchPlaceholder:"Search a lesson, a word, a dish…",
    searchPlaceholderCulture:"Search a recipe, a rhythm, a destination…",
    lessonCount:(n)=>`${n} lesson${n!==1?'s':''}`,
    recipeCount:(n)=>`${n} recipe${n!==1?'s':''}`,
    expressionCount:(n)=>`${n} expression${n!==1?'s':''}`,
    styleCount:(n)=>`${n} style${n!==1?'s':''}`,
    sectionTitles:{ langue:"Language lessons", cuisine:"Creole cuisine", voyage:"Travel expressions", musique:"Creole music", apropos:"About Krēolia", communaute:"Guestbook" },
    heroBtnP_langue:"Start from scratch",
    heroBtnS_langue:"I already understand",
    heroBtnP_culture:"Explore culture",
    heroBtnS_culture:"See all",
    heroBtnP_apropos:"Discover Krēolia",
    heroBtnS_apropos:"Creole families",
    heroBtnP_communaute:"Read the journal",
    heroBtnS_communaute:"Leave a message",
    communautePostBtn:"Post",
    communautePostPlaceholder:"Share a thought, a question, a discovery…",
    communauteLoginPrompt:"Log in to post a message.",
    loginBtn:"Log in",
    logoutBtn:"✕ Log out",
    loginTitle:"Log in",
    registerTitle:"Sign up",
    loginSubmit:"Log in",
    registerSubmit:"Create account",
    loginSwitch:"No account yet?",
    loginSwitchLink:"Sign up",
    registerSwitch:"Already have an account?",
    registerSwitchLink:"Log in",
    fieldEmail:"Email",
    fieldPassword:"Password",
    fieldPseudo:"Username",
    fieldPasswordHint:"(min. 6 characters)",
    footerFamilies:"Creole families",
    footerNav:"Navigation",
    footerTaglineSuffix:"All the world's creoles, one platform.",
    bases:{"FR-based":"French","EN-based":"English","PT-based":"Portuguese","ES-based":"Spanish","NL-based":"Dutch","AR-based":"Arabic","Malay-based":"Malay"},
    v2label:"(v2)",
    comingSoon:"Coming soon",
    noLesson:"No lesson found.",
    noContent:"Content coming soon.",
  },
  es:{
    langue:"Idioma", culture:"Cultura", apropos:"Acerca de", communaute:"Comunidad",
    cultureSubTabs:{ voyage:"Viaje", cuisine:"Cocina", musique:"Música" },
    chipLabel:"Familia criolla basada en",
    searchPlaceholder:"Buscar una lección, una palabra…",
    searchPlaceholderCulture:"Buscar una receta, un ritmo, un destino…",
    lessonCount:(n)=>`${n} lección${n!==1?'es':''}`,
    recipeCount:(n)=>`${n} receta${n!==1?'s':''}`,
    expressionCount:(n)=>`${n} expresión${n!==1?'es':''}`,
    styleCount:(n)=>`${n} estilo${n!==1?'s':''}`,
    sectionTitles:{ langue:"Lecciones de idioma", cuisine:"Cocina criolla", voyage:"Expresiones de viaje", musique:"Música criolla", apropos:"Acerca de Krēolia", communaute:"Diario" },
    heroBtnP_langue:"Empezar desde cero",
    heroBtnS_langue:"Ya entiendo",
    heroBtnP_culture:"Explorar la cultura",
    heroBtnS_culture:"Ver todo",
    heroBtnP_apropos:"Descubrir Krēolia",
    heroBtnS_apropos:"Familias criollas",
    heroBtnP_communaute:"Leer el diario",
    heroBtnS_communaute:"Dejar un mensaje",
    communautePostBtn:"Publicar",
    communautePostPlaceholder:"Comparte un pensamiento, una pregunta…",
    communauteLoginPrompt:"Inicia sesión para publicar un mensaje.",
    loginBtn:"Iniciar sesión",
    logoutBtn:"✕ Salir",
    loginTitle:"Iniciar sesión",
    registerTitle:"Registrarse",
    loginSubmit:"Iniciar sesión",
    registerSubmit:"Crear cuenta",
    loginSwitch:"¿Sin cuenta aún?",
    loginSwitchLink:"Registrarse",
    registerSwitch:"¿Ya tienes cuenta?",
    registerSwitchLink:"Iniciar sesión",
    fieldEmail:"Correo",
    fieldPassword:"Contraseña",
    fieldPseudo:"Nombre de usuario",
    fieldPasswordHint:"(mín. 6 caracteres)",
    footerFamilies:"Familias criollas",
    footerNav:"Navegación",
    footerTaglineSuffix:"Todos los criollos del mundo, una plataforma.",
    bases:{"FR-based":"francés","EN-based":"inglés","PT-based":"portugués","ES-based":"español","NL-based":"neerlandés","AR-based":"árabe","Malay-based":"malayo"},
    v2label:"(v2)",
    comingSoon:"Próximamente",
    noLesson:"No se encontró ninguna lección.",
    noContent:"Contenido próximamente.",
  },
  pt:{
    langue:"Língua", culture:"Cultura", apropos:"Sobre", communaute:"Comunidade",
    cultureSubTabs:{ voyage:"Viagem", cuisine:"Cozinha", musique:"Música" },
    chipLabel:"Família crioula baseada em",
    searchPlaceholder:"Pesquisar uma lição, uma palavra…",
    searchPlaceholderCulture:"Pesquisar uma receita, um ritmo, um destino…",
    lessonCount:(n)=>`${n} lição${n!==1?'ões':''}`,
    recipeCount:(n)=>`${n} receita${n!==1?'s':''}`,
    expressionCount:(n)=>`${n} expressão${n!==1?'ões':''}`,
    styleCount:(n)=>`${n} estilo${n!==1?'s':''}`,
    sectionTitles:{ langue:"Lições de língua", cuisine:"Cozinha crioula", voyage:"Expressões de viagem", musique:"Música crioula", apropos:"Sobre Krēolia", communaute:"Diário" },
    heroBtnP_langue:"Começar do zero",
    heroBtnS_langue:"Já compreendo",
    heroBtnP_culture:"Explorar a cultura",
    heroBtnS_culture:"Ver tudo",
    heroBtnP_apropos:"Descobrir Krēolia",
    heroBtnS_apropos:"Famílias crioulas",
    heroBtnP_communaute:"Ler o diário",
    heroBtnS_communaute:"Deixar uma mensagem",
    communautePostBtn:"Publicar",
    communautePostPlaceholder:"Partilhe um pensamento, uma pergunta…",
    communauteLoginPrompt:"Inicie sessão para publicar uma mensagem.",
    loginBtn:"Entrar",
    logoutBtn:"✕ Sair",
    loginTitle:"Entrar",
    registerTitle:"Registar",
    loginSubmit:"Entrar",
    registerSubmit:"Criar conta",
    loginSwitch:"Ainda sem conta?",
    loginSwitchLink:"Registar",
    registerSwitch:"Já tem conta?",
    registerSwitchLink:"Entrar",
    fieldEmail:"E-mail",
    fieldPassword:"Palavra-passe",
    fieldPseudo:"Nome de utilizador",
    fieldPasswordHint:"(mín. 6 caracteres)",
    footerFamilies:"Famílias crioulas",
    footerNav:"Navegação",
    footerTaglineSuffix:"Todos os crioulos do mundo, uma plataforma.",
    bases:{"FR-based":"francês","EN-based":"inglês","PT-based":"português","ES-based":"espanhol","NL-based":"neerlandês","AR-based":"árabe","Malay-based":"malaio"},
    v2label:"(v2)",
    comingSoon:"Em breve",
    noLesson:"Nenhuma lição encontrada.",
    noContent:"Conteúdo em breve.",
  },
  nl:{
    langue:"Taal", culture:"Cultuur", apropos:"Over ons", communaute:"Gemeenschap",
    cultureSubTabs:{ voyage:"Reizen", cuisine:"Keuken", musique:"Muziek" },
    chipLabel:"Creoolse taalfamilie op basis van",
    searchPlaceholder:"Zoek een les, een woord…",
    searchPlaceholderCulture:"Zoek een recept, een ritme, een bestemming…",
    lessonCount:(n)=>`${n} les${n!==1?'sen':''}`,
    recipeCount:(n)=>`${n} recept${n!==1?'en':''}`,
    expressionCount:(n)=>`${n} uitdrukking${n!==1?'en':''}`,
    styleCount:(n)=>`${n} stijl${n!==1?'en':''}`,
    sectionTitles:{ langue:"Taallessen", cuisine:"Creoolse keuken", voyage:"Reisuitdrukkingen", musique:"Creoolse muziek", apropos:"Over Krēolia", communaute:"Dagboek" },
    heroBtnP_langue:"Begin vanaf nul",
    heroBtnS_langue:"Ik begrijp al",
    heroBtnP_culture:"Cultuur verkennen",
    heroBtnS_culture:"Alles zien",
    heroBtnP_apropos:"Krēolia ontdekken",
    heroBtnS_apropos:"Creoolse families",
    heroBtnP_communaute:"Dagboek lezen",
    heroBtnS_communaute:"Bericht achterlaten",
    communautePostBtn:"Plaatsen",
    communautePostPlaceholder:"Deel een gedachte, een vraag…",
    communauteLoginPrompt:"Log in om een bericht te plaatsen.",
    loginBtn:"Inloggen",
    logoutBtn:"✕ Uitloggen",
    loginTitle:"Inloggen",
    registerTitle:"Registreren",
    loginSubmit:"Inloggen",
    registerSubmit:"Account aanmaken",
    loginSwitch:"Nog geen account?",
    loginSwitchLink:"Registreren",
    registerSwitch:"Al een account?",
    registerSwitchLink:"Inloggen",
    fieldEmail:"E-mail",
    fieldPassword:"Wachtwoord",
    fieldPseudo:"Gebruikersnaam",
    fieldPasswordHint:"(min. 6 tekens)",
    footerFamilies:"Creoolse families",
    footerNav:"Navigatie",
    footerTaglineSuffix:"Alle creoolse talen, één platform.",
    bases:{"FR-based":"Frans","EN-based":"Engels","PT-based":"Portugees","ES-based":"Spaans","NL-based":"Nederlands","AR-based":"Arabisch","Malay-based":"Maleis"},
    v2label:"(v2)",
    comingSoon:"Binnenkort",
    noLesson:"Geen les gevonden.",
    noContent:"Inhoud binnenkort beschikbaar.",
  },
  ar:{
    langue:"اللغة", culture:"الثقافة", apropos:"حول", communaute:"المجتمع",
    cultureSubTabs:{ voyage:"سفر", cuisine:"مطبخ", musique:"موسيقى" },
    chipLabel:"عائلة الكريول المبنية على",
    searchPlaceholder:"ابحث عن درس أو كلمة…",
    searchPlaceholderCulture:"ابحث عن وصفة أو إيقاع أو وجهة…",
    lessonCount:(n)=>`${n} درس`,
    recipeCount:(n)=>`${n} وصفة`,
    expressionCount:(n)=>`${n} تعبير`,
    styleCount:(n)=>`${n} أسلوب`,
    sectionTitles:{ langue:"دروس اللغة", cuisine:"المطبخ الكريولي", voyage:"تعبيرات السفر", musique:"موسيقى كريولية", apropos:"حول Krēolia", communaute:"مذكرات" },
    heroBtnP_langue:"ابدأ من الصفر",
    heroBtnS_langue:"أنا أفهم بالفعل",
    heroBtnP_culture:"استكشف الثقافة",
    heroBtnS_culture:"عرض الكل",
    heroBtnP_apropos:"اكتشف Krēolia",
    heroBtnS_apropos:"العائلات الكريولية",
    heroBtnP_communaute:"اقرأ المذكرات",
    heroBtnS_communaute:"اترك رسالة",
    communautePostBtn:"نشر",
    communautePostPlaceholder:"شارك فكرة أو سؤالاً…",
    communauteLoginPrompt:"سجّل الدخول لنشر رسالة.",
    loginBtn:"تسجيل الدخول",
    logoutBtn:"✕ خروج",
    loginTitle:"تسجيل الدخول",
    registerTitle:"إنشاء حساب",
    loginSubmit:"دخول",
    registerSubmit:"إنشاء حساب",
    loginSwitch:"ليس لديك حساب؟",
    loginSwitchLink:"سجّل",
    registerSwitch:"لديك حساب؟",
    registerSwitchLink:"سجّل دخولك",
    fieldEmail:"البريد الإلكتروني",
    fieldPassword:"كلمة المرور",
    fieldPseudo:"اسم المستخدم",
    fieldPasswordHint:"(٦ أحرف على الأقل)",
    footerFamilies:"العائلات الكريولية",
    footerNav:"التنقل",
    footerTaglineSuffix:"كل الكريول في العالم، منصة واحدة.",
    bases:{"FR-based":"الفرنسية","EN-based":"الإنجليزية","PT-based":"البرتغالية","ES-based":"الإسبانية","NL-based":"الهولندية","AR-based":"العربية","Malay-based":"الماليزية"},
    v2label:"(v2)",
    comingSoon:"قريباً",
    noLesson:"لم يتم العثور على درس.",
    noContent:"المحتوى قريباً.",
  },
  ms:{
    langue:"Bahasa", culture:"Budaya", apropos:"Tentang", communaute:"Komuniti",
    cultureSubTabs:{ voyage:"Perjalanan", cuisine:"Masakan", musique:"Muzik" },
    chipLabel:"Keluarga kreol berasaskan",
    searchPlaceholder:"Cari pelajaran, perkataan…",
    searchPlaceholderCulture:"Cari resipi, irama, destinasi…",
    lessonCount:(n)=>`${n} pelajaran`,
    recipeCount:(n)=>`${n} resipi`,
    expressionCount:(n)=>`${n} ungkapan`,
    styleCount:(n)=>`${n} gaya`,
    sectionTitles:{ langue:"Pelajaran bahasa", cuisine:"Masakan kreol", voyage:"Ungkapan perjalanan", musique:"Muzik kreol", apropos:"Tentang Krēolia", communaute:"Jurnal" },
    heroBtnP_langue:"Mulai dari awal",
    heroBtnS_langue:"Saya sudah faham",
    heroBtnP_culture:"Jelajahi budaya",
    heroBtnS_culture:"Lihat semua",
    heroBtnP_apropos:"Temui Krēolia",
    heroBtnS_apropos:"Keluarga kreol",
    heroBtnP_communaute:"Baca jurnal",
    heroBtnS_communaute:"Tinggalkan mesej",
    communautePostBtn:"Hantar",
    communautePostPlaceholder:"Kongsikan pemikiran, soalan…",
    communauteLoginPrompt:"Log masuk untuk menghantar mesej.",
    loginBtn:"Log masuk",
    logoutBtn:"✕ Keluar",
    loginTitle:"Log masuk",
    registerTitle:"Daftar",
    loginSubmit:"Log masuk",
    registerSubmit:"Buat akaun",
    loginSwitch:"Tiada akaun lagi?",
    loginSwitchLink:"Daftar",
    registerSwitch:"Sudah ada akaun?",
    registerSwitchLink:"Log masuk",
    fieldEmail:"E-mel",
    fieldPassword:"Kata laluan",
    fieldPseudo:"Nama pengguna",
    fieldPasswordHint:"(min. 6 aksara)",
    footerFamilies:"Keluarga kreol",
    footerNav:"Navigasi",
    footerTaglineSuffix:"Semua kreol dunia, satu platform.",
    bases:{"FR-based":"Perancis","EN-based":"Inggeris","PT-based":"Portugis","ES-based":"Sepanyol","NL-based":"Belanda","AR-based":"Arab","Malay-based":"Melayu"},
    v2label:"(v2)",
    comingSoon:"Akan datang",
    noLesson:"Tiada pelajaran ditemui.",
    noContent:"Kandungan akan datang.",
  },
};

/* ============================================================
   LANGUES UI DISPONIBLES (v1 actives, v2 grisées)
   ============================================================ */
export const UI_LANGUAGES = [
  {code:"fr", label:"FR", v2:false},
  {code:"en", label:"EN", v2:false},
  {code:"es", label:"ES", v2:false},
  {code:"pt", label:"PT", v2:false},
  {code:"nl", label:"NL", v2:false},
  {code:"ar", label:"AR", v2:false},
  {code:"ms", label:"MS", v2:false},
  /* Langues créoles — v2 */
  {code:"gcf", label:"Kréyòl GWA", v2:true},
  {code:"hat", label:"Kreyòl AYI", v2:true},
  {code:"jam", label:"Patois JAM", v2:true},
  {code:"kea", label:"Kabuverdianu", v2:true},
  {code:"pap", label:"Papiamentu", v2:true},
  {code:"pga", label:"Juba AR", v2:true},
  {code:"bew", label:"Betawi", v2:true},
];
